### ISSUE TITLE
Spotify cannot connect behind HTTP proxy (Privoxy) in Linux Mint 17.3)

### ISSUE THREAD

**Issue by TrevorScheitrum** [tiliado/nuvola-app-spotify#13] opened 2016-05-26 22:00 UTC
Spotify uses the WebSockets technology. Unfortunately, this technology doesn't work behind HTTP proxy in older versions of WebKitGTK+ and libsoup libraries. **The issue seems to be fixed in libsoup 2.50 and WebKitGTK+ 2.8**. Please upgrade your libraries if you need proxy support for Spotify. This may require an upgrade to a new release of your linux distribution.

---

Tasks:
- [x] Check whether libsoup 2.50 + WebKitGTK+ 2.8 also work. It works.
- [x] Add a note about this issue to [the documentation](https://github.com/tiliado/nuvola-app-spotify/wiki/Known-Issues).
- [x] Write page [WebKitGTK Upgrade](https://github.com/tiliado/nuvolaplayer/wiki/WebKitGTK-Upgrade)
- [x] Merge the branch with the upgrade request.

---
**Original report: Privoxy and spotify: does proxy work?**

Hello,

I'm trying to set up Privoxy and use the Nuvola Player for Spotify on the same machine.  I can't seem to get the proxy settings in nuvolaplayer3 to allow me to authenticate and access spotify (screenshot included).  I tried to research this a little bit and noticed this was a bug in version 2 of Nuvola player, not sure if its been fixed in version 3, or this is still an outstanding bug.  Any thoughts?

(in the settings i tried both 127.0.0.1 and localhost just to make sure, and it still doesn't work)

![screenshot from 2016-05-26 14 58 47](https://cloud.githubusercontent.com/assets/1857060/15591505/62c2d50c-2352-11e6-84eb-acfa418acb87.png)

/etc/privoxy/config

![screenshot from 2016-05-26 15 03 35](https://cloud.githubusercontent.com/assets/1857060/15591646/0f2853da-2353-11e6-937e-2753b896f349.png)

**Comment by fenryxo** [comment] 2016-05-29 21:45
Hello @TrevorScheitrum. Unfortunately, Spotify doesn't work behind HTTP proxy in both WebKitGTK+ and Firefox on my system but it works in Chromium. The issue is probably incomplete proxy support in the WebSockets technology. There are two upstream bugs - [WebKitGTK+ Bug 126384 - Proxied WebSockets with soup network backend](https://bugs.webkit.org/show_bug.cgi?id=126384) (not yet fixed but does have a patch) and [libsoup Bug 721343 - Add API to establish proxy-tunnelled connection](https://bugzilla.gnome.org/show_bug.cgi?id=721343) (already fixed) - so it may be possible to get Web Sockets working in Nuvola Player.

Which linux distribution & version do you use?

**Comment by TrevorScheitrum** [comment] 2016-05-30 02:09
Hi @fenryxo, thanks for the reply!   I'm using Linux Mint 17.3 and Ubuntu 16.04, both debian based, and both seem to have this issue. 

NuvolaPlayer3, version: 3.0.2
Spotify Plugin version: 2.1
Web Engine: WebKitGTK 2.8.5

**Comment by fenryxo** [comment] 2016-05-30 08:53
> I just installed this on an Ubuntu 16.04 machine, and Proxy settings work with WebKit version 2.10.9

Oh, great. The issue seems to have been fixed upstream after all :-) The necessary API seems to be included in libsoup 2.50 (Ubuntu 15.10) but I'm not sure which is the minimal required WebKitGTK version (Ubuntu 15.10 has libwebkit2gtk-4.0-37 2.8.5+dfsg1-3). I'll check that later.

> I'm using Linux Mint 17.3 

Unfortunately, Linux Mint 17.3 is based on Ubuntu 14.04 and has old libraries. It might be possible to backport libsoup 2.50 somehow and then install [a recent WebKitGTK](https://launchpad.net/~nuvola-player-builders/+archive/ubuntu/webkit). However, I don't plan any libsoup backporting due to a lack of funds.

**Comment by fenryxo** [comment] 2016-06-01 14:06
A combination of libsoup 2.50 + WebKitGTK+ 2.8 in Ubuntu 15.10 also work.

**Comment by fenryxo** [comment] 2016-07-23 08:50
I've added this issue to [the Known Issues wiki page](https://github.com/tiliado/nuvola-app-spotify/wiki/Known-Issues).

**Comment by fenryxo** [comment] 2016-08-22 13:09
PR #16

**Comment by fenryxo** [comment] 2016-08-27 14:22
This issue has been fixed in release 2.2. Thanks for your bug report.

**Closed by fenryxo** 2016-08-27 14:22 UTC
Labels: bug
