### ISSUE TITLE
Spotify Ads louder than actual songs

### ISSUE THREAD

**Issue by snoopsean** [tiliado/nuvola-app-spotify#6] opened 2015-07-18 13:18 UTC
Im on debian jessie.
Nuvola player 3.0.0+201507151301.37fe120
Spotify version 2.1

I just updated last night with latest version of both. It seems like the Spotify ads are now much louder than the songs, so I notice having to turn down the volume during the commercials. 

Im not sure if this is the spotify plugin or nuvola itself.

BT dubs, this is fantastic software, thank you so much for all the work you do.

**Comment by fenryxo** [comment] 2015-07-18 13:29
Hello @snoopsean. Thanks for your bug report. Does this issue also happen in Firefox, Epiphany (GNOME Web) or Chrome?

**Comment by snoopsean** [comment] 2015-07-19 05:29
just tried in firefox version 39 for x86_64 linux. sound volume for commercials vs songs was not different like it was for the nuvola plugin.

in chrome, i had no problems either.

let me know if you want me to do epiphany as well.

**Comment by fenryxo** [comment] 2015-07-19 06:51
Spotify seems to use Flash to play music (WebKitPluginProcess2 with Flash using ALSA PulseAudio plug-in) and HTML5 audio for commercials (WebKiWebProcess plays via GStreamer without ALSA). Unfortunately, volume of these streams is not in sync in your case. However, they are in sync on my system. Do you have enabled PulseAudio flat volumes?

```
$ grep flat-volumes /etc/pulse/* ~/.pulse/* 2>/dev/null
/etc/pulse/daemon.conf:; flat-volumes = yes
```

**Comment by snoopsean** [comment] 2015-07-20 21:08
i do. when i ran the command: 
grep flat-volumes /etc/pulse/* ~/.pulse/* 2>/dev/null

I got the result of:
/etc/pulse/daemon.conf:; flat-volumes = yes

When a commercial comes up, Im just going to go into pulse audio and set the commercial volume to the same as the song volume and see if it sticks.

Do you know why it uses flash for songs and html5 for commercials, as opposed to just using html5 for both?

Ill update this when I've manually matched the commercial volume and song volume. Ill let you know if it sticks, or if it keeps going back to being out of sync.

**Comment by snoopsean** [comment] 2015-07-25 05:11
at this point im really confused. Once i set the music (webkitprocess2) volume to 100 percent, then i turned down the master volume, the music volume followed suit . If you try to turn down the music volume in pulse audio, the master volume will not follow suit.

So if i have the master volume at 60 percent, and the music volume at about the same spot, and then the commercial (webkitprocess) comes on, it will switch the master volume to 100 percent! The commercial volume will also be at 100 percent. It does not raise the music volume.

So even though i resynced the music volume with the master volume, whenever a commercial volume comes on it will switch the master volume itself.

Its kind on out of the ordinary so i have tested multiple times, and i continue to have it repeat the same problem.

here is the pulse audio during music
![musicandmastersame](https://cloud.githubusercontent.com/assets/7492437/8888026/aab153aa-3250-11e5-9939-2b77fe1db1fa.png)

here is the pulse audio when a commercial starts. note i did not touch the volume controls, it just set the master voulme on its own.
![commercialsetsvolume](https://cloud.githubusercontent.com/assets/7492437/8888028/bd0761c0-3250-11e5-88e3-21690c97f42d.png)

here is pulse audio after
![musicandmasterafter](https://cloud.githubusercontent.com/assets/7492437/8888030/d104da2c-3250-11e5-9e60-5e253f61def6.png)

Let me know what you think. Thanks again for responding so quickly

**Comment by fenryxo** [comment] 2015-07-25 09:19
Hello. I'll take a look at this issue in [August 2015](https://github.com/tiliado/nuvolaplayer.project/issues/5) as [funds for July 2015](https://tiliado.eu/nuvolaplayer/funding/tasks/201507/) have been already almost spent. Thanks for your understanding.

**Comment by snoopsean** [comment] 2015-07-25 09:20
thank you so much. no rush, ppl can work around it if needed
		
        
		-Sean Lancaster
		 ---- On Sat, 25 Jul 2015 02:19:33 -0700  notifications@github.com  wrote ----Hello. I'll take a look at this issue in August 2015 as funds for July 2015 have been already almost spent. Thanks for your understanding.

**Comment by fenryxo** [comment] 2015-08-02 16:54
> Do you know why it uses flash for songs and html5 for commercials, as opposed to just using html5 for both?

Maybe flash is necessary because of DRM and commercials doesn't require DRM.

> at this point im really confused. Once i set the music (webkitprocess2) volume to 100 percent, then i turned down the master volume, the music volume followed suit . If you try to turn down the music volume in pulse audio, the master volume will not follow suit.

This is expected behavior with `flat-volumes = yes`. The volumes of input streams (e.g. webkitprocess2) and output stream (master volume as you call it) are relative to the maximal sound card (hardware) volume in this mode and the output stream (master) volume is always equal or greater than the volume of the loudest input stream.

If you set music input stream (webkitprocess2) to 100% (=100% of the maximal hardware volume), the output stream volume (master volume) is also set to 100% (=100% of the maximal hardware volume), because the output stream volume must be always equal or greater than the volume of the loudest input stream. If you decrease the output stream volume (master volume) to 80% (=80% of the maximal hardware volume), all input streams (e.g. webkitprocess2) must also be changed to have volume 80% (=80% of the maximal hardware volume) or less, because the output stream volume must be always equal or greater than the volume of the loudest input stream. However, if you decrease the music input stream (webkitprocess2) to 80% (=80% of the maximal hardware volume), the output stream volume (master volume) is left unchanged at 100%, because it already is equal or greater than the volume of the loudest input stream.

> So if i have the master volume at 60 percent, and the music volume at about the same spot, and then the commercial (webkitprocess) comes on, it will switch the master volume to 100 percent! The commercial volume will also be at 100 percent. It does not raise the music volume.

Again, this is expected behavior with `flat-volumes = yes`. If you have set the music input stream (webkitprocess2) to 60% (=60% of the maximal hardware volume), the output stream volume (master volume) must be set to 60% (=60% of the maximal hardware volume) or more, because the output stream volume must be always equal or greater than the volume of the loudest input stream. When a new input stream (commercials) with volume 100% (=100% of the maximal hardware volume) appears, the output stream volume (master volume) must be set to 100% (=100% of the maximal hardware volume), because the output stream volume must be always equal or greater than the volume of the loudest input stream. However, other input streams are independent and their volume is unchanged. The volume of the music stream is not raised, because it has been set to 60%  (=60% of the maximal hardware volume) before and nobody has requested to change it since than.


I will try to find a solution when I will have some free time at work as Spotify doesn't work with my home internet connection because of a proxy server.

**Comment by snoopsean** [comment] 2015-08-02 20:31
thank you for the explanation.
		
        
		-Sean Lancaster
		 ---- On Sun, 02 Aug 2015 09:54:29 -0700  notifications@github.com  wrote ----
Do you know why it uses flash for songs and html5 for commercials, as opposed to just using html5 for both?

Maybe flash is necessary because of DRM and commercials doesn't require DRM.

at this point im really confused. Once i set the music (webkitprocess2) volume to 100 percent, then i turned down the master volume, the music volume followed suit . If you try to turn down the music volume in pulse audio, the master volume will not follow suit.

This is expected behavior with flat-volumes = yes. The volumes of input streams (e.g. webkitprocess2) and output stream (master volume as you call it) are relative to the maximal sound card (hardware) volume in this mode and the output stream (master) volume is always equal or greater than the volume of the loudest input stream.
If you set music input stream (webkitprocess2) to 100% (=100% of the maximal hardware volume), the output stream volume (master volume) is also set to 100% (=100% of the maximal hardware volume), because the output stream volume must be always equal or greater than the volume of the loudest input stream. If you decrease the output stream volume (master volume) to 80% (=80% of the maximal hardware volume), all input streams (e.g. webkitprocess2) must also be changed to have volume 80% (=80% of the maximal hardware volume) or less, because the output stream volume must be always equal or greater than the volume of the loudest input stream. However, if you decrease the music input stream (webkitprocess2) to 80% (=80% of the maximal hardware volume), the output stream volume (master volume) is left unchanged at 100%, because it already is equal or greater than the volume of the loudest input stream.

So if i have the master volume at 60 percent, and the music volume at about the same spot, and then the commercial (webkitprocess) comes on, it will switch the master volume to 100 percent! The commercial volume will also be at 100 percent. It does not raise the music volume.

Again, this is expected behavior with flat-volumes = yes. If you have set the music input stream (webkitprocess2) to 60% (=60% of the maximal hardware volume), the output stream volume (master volume) must be set to 60% (=60% of the maximal hardware volume) or more, because the output stream volume must be always equal or greater than the volume of the loudest input stream. When a new input stream (commercials) with volume 100% (=100% of the maximal hardware volume) appears, the output stream volume (master volume) must be set to 100% (=100% of the maximal hardware volume), because the output stream volume must be always equal or greater than the volume of the loudest input stream. However, other input streams are independent and their volume is unchanged. The volume of the music stream is not raised, because it has been set to 60%  (=60% of the maximal hardware volume) before and nobody has requested to change it since than.
I will try to find a solution when I will have some free time at work as Spotify doesn't work with my home internet connection because of a proxy server.

**Comment by fenryxo** [comment] 2015-08-03 12:18
Hello. What volume do you have actually set in the Spotify web interface (the volume slider in the right sidebar of the web page)?

**Comment by snoopsean** [comment] 2015-08-03 19:08
full
		
        
		-Sean Lancaster
		 ---- On Mon, 03 Aug 2015 05:18:25 -0700  notifications@github.com  wrote ----Hello. What volume do you have actually set in the Spotify web interface (the volume slider in the right sidebar of the web page)?

**Comment by fenryxo** [comment] 2015-08-05 09:12
Hello. I've described this issue in detail and added workarounds in [Spotify's Known Issues wiki page](https://github.com/tiliado/nuvola-app-spotify/wiki/Known-Issues). Could you take a look at it and provide feedback?

**Comment by fenryxo** [comment] 2015-08-05 09:13
@thenyeguy, could you also look at the  [Spotify's Known Issues wiki page](https://github.com/tiliado/nuvola-app-spotify/wiki/Known-Issues) and tell me whether it makes sense to you?

**Comment by snoopsean** [comment] 2015-08-12 05:58
ok i just set flat volumes to no. I did the other steps as well, and now i just use the spotify web app volume control (not master or the webkitprocess2). that works really well. ill try using the master volume to do everything as well and report back. for now, using the spotify web player volume bar works though

**Comment by snoopsean** [comment] 2015-08-12 06:17
ok i used the master volume to lower it to about 50 percent, which lowered the webkitprocess2. i had the spotify web app bar at full. when a commercial came on, it still knocked my master volume to 100 percent, even with flat-volumes set to no. ill try a restart and report back, but at this point that piece doesnt seem to work.

**Comment by fenryxo** [comment] 2015-08-12 07:08
> ill try a restart and report back, but at this point that piece doesnt seem to work.

It is necessary to restart PulseAudio or reboot to apply changes in PulseAudio configuration. I've just added this information to the wiki page :-)

**Comment by snoopsean** [comment] 2015-08-12 07:15
I restarted, but I still have the same problem. The fix using the spotify web player sound bar does continue to work, though. Changing the master volume doesnt seem to stick even with flat-volumes set to no.

**Comment by fenryxo** [comment] 2015-08-12 07:16
Could you post output of `grep flat-volumes /etc/pulse/* ~/.pulse/* 2>/dev/null` to be sure the configuration is right?

**Comment by snoopsean** [comment] 2015-08-12 07:18
tvjohnny@2trill ~ $ grep flat-volumes /etc/pulse/* ~/.pulse/* 2>/dev/null
/etc/pulse/daemon.conf:; flat-volumes = no

**Comment by fenryxo** [comment] 2015-08-12 07:19
This option is commented out. Remove the semicolon `;` at the beginning of the line.

**Comment by snoopsean** [comment] 2015-08-12 20:34
ok i removed the semicolon (i thought only the # was for comments) and restarted my machine. I set the webkitprocess2 to 100. the spotify web app sound is also at 100. i set the master volume to 0, and started spotify. i now have the master volume at around 55. 
![beforepulsaaudio](https://cloud.githubusercontent.com/assets/7492437/9235924/9dd40d9e-40f6-11e5-8feb-d7a298ce822b.png)
when the commercial came on, the commercial was not at full volume, and it didnt change the master voulme. note it wasnt at 50 percent like my master volume (maybe 705 or 80 percent), but certainly not louder than the regular music.
![afterpulseaudio](https://cloud.githubusercontent.com/assets/7492437/9235952/c9b1073c-40f6-11e5-951f-23b54861720c.png)


thanks again @fenryxo

**Comment by fenryxo** [comment] 2015-08-13 08:43
To sum up, if I understand your comment, the issue is solved for you (although with a workaround) and I can close it. Am I right?

> when the commercial came on, the commercial was not at full volume, and it didnt change the master voulme.

 Great :-)

> note it wasnt at 50 percent like my master volume (maybe 705 or 80 percent), but certainly not louder than the regular music.

Yes, master volume and volumes of particular streams are independent with flat-volumes disabled. I'm wondering where the70-80% volume came from. Have you set the volume bar inside Spotify web page to 70-80%?

**Comment by snoopsean** [comment] 2015-08-13 09:53
yes its resolved with the workaround. thanks again. no i didnt set the spotify web app bar to 70 80, it was at 100
		
        
		-Sean Lancaster
		 ---- On Thu, 13 Aug 2015 01:43:29 -0700  notifications@github.com  wrote ----To sum up, if I understand your comment, the issue is solved for you (although with a workaround) and I can close it. Am I right?

when the commercial came on, the commercial was not at full volume, and it didnt change the master voulme.

Great :-)

note it wasnt at 50 percent like my master volume (maybe 705 or 80 percent), but certainly not louder than the regular music.

Yes, master volume and volumes of particular streams are independent with flat-volumes disabled. I'm wondering where the70-80% volume came from. Have you set the volume bar inside Spotify web page to 70-80%?

**Closed** 2015-08-13 10:37 UTC
Labels: more info required

**Comment by fenryxo** [comment] 2015-08-13 22:28
Follow up: tiliado/nuvolaplayer#138
