### ISSUE TITLE
When clicking the play button next to a song on the artist panel, window shifts out

### ISSUE THREAD

**Issue by snoopsean** [tiliado/nuvola-app-spotify#7] opened 2015-08-15 23:35 UTC
When I am in the spotify app, and I click on an artist in my songs list, it takes me to their page. If i try to press the play button next to a particular song, the window shifts out.

Note Im on debian Jessie 64 bit. I have the latest nuvola update
3.0.0+201508132008.c260a4d

I have a video that I will upload shortly its 2 minutes and 8 seconds. There were a couple times where i was able to get it to work. I clicked on the play button, and the window shifted, but then it shifted back. I clicked the play button again and it started playing.

I was hoping you could spot the problem, or let me know if you have any more steps you want me to try

https://youtu.be/Yu8qDnd4Cl0

Update: I know it has to do with the window resizing. If i resize the window (either maximize it or normalize it), I can then play the song. Ill upload another video here. There has been one time where resizing didnt help (just  a white space on the right side of the window), but clicking around on the left panel fixed it.

https://youtu.be/nl0VhKVYh58

**Comment by fenryxo** [comment] 2015-08-16 07:51
Hello. Thanks for taking the time to report this issue. Is it reproducible in WebKitGtk MiniBrowser?

* `/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/MiniBrowser` (64bit system)
* `/usr/lib/i386-linux-gnu/webkit2gtk-4.0/MiniBrowser` (32bit system)

**Comment by snoopsean** [comment] 2015-08-16 18:18
yes, i got the same problem in the minibrowser. window resizing fixed the problem, just like in the nuvola app as well.

**Comment by fenryxo** [comment] 2015-08-16 18:20
Well, it looks like a bug in WebKitGtk or Spotify code then. Does it also happen in other browsers like Firefox/Chrome?

**Comment by snoopsean** [comment] 2015-08-17 00:00
it does not happen in firefox or chrome.

**Comment by snoopsean** [comment] 2015-08-17 01:01
so it looks like a webkitgtk problem. unfortunately, I tried to build the latest version of webkitgtk, but the documentation for building is outdated. although I was able to get all the dependencies, i wasnt able to build the jhbuild modules. I could not find the specific update-webkitgtk-libs script or anything like it in the entire download. I tried 2.85 (the latest stable), and 2.9.90 (the latest unstable).

I went to the debian package tracker, that didnt help. It looks like im running webkitgtk 2.6.2 (so a little behind). I then went to linuxfromscratch and tried to follow their directions to build this. unfortunately, I got sucked into dependency hell.

This is way to complex for me :(

Id say for now, if anyone out there has the same problem as me, just resize the window until they update webkitgtk for your distribution.

**Comment by fenryxo** [comment] 2015-08-18 09:58
> Id say for now, if anyone out there has the same problem as me, just resize the window until they update webkitgtk for your distribution.

You seems to assume the issue is fixed in the latest webkitgtk, but there is no evidence for that.

**Comment by snoopsean** [comment] 2015-08-18 19:33
I'm saying there is no fix now that i can get, but there MAY be a fix with the next webkit2gtk.
		
        
		-Sean Lancaster
		 ---- On Tue, 18 Aug 2015 02:58:55 -0700  notifications@github.com  wrote ----
Id say for now, if anyone out there has the same problem as me, just resize the window until they update webkitgtk for your distribution.

You seems to assume the issue is fixed in the latest webkitgtk, but there is no evidence for that.

**Comment by fenryxo** [comment] 2015-08-31 08:54
It is necessary to reproduce the issue in the jhbuild of the WebKitGTK and forward it upstream. I'll take care of it.

**Comment by fenryxo** [comment] 2016-05-30 12:37
Hello. Does the issue happen with WebKitGTK 2.12 (available in jessie-backports)?

**Comment by fenryxo** [comment] 2016-07-03 18:42
No feedback for a month, closing.

**Closed by fenryxo** 2016-07-03 18:42 UTC
Labels: bug, more info required
