### ISSUE TITLE
This browser is not compatible with Spotify web player

### ISSUE THREAD

**Issue by leandroramos** [tiliado/nuvola-app-spotify#21] opened 2018-01-08 13:46 UTC
Hi.
When I open the app, I get this error and cannot play songs.

Screenshot:
https://ibb.co/bxKMGm

Best regards.

**Comment by fenryxo** [comment] 2018-01-08 15:03
Hello @leandroramos. Nuvola 4.10 will support Spotify again. Nuvola Premium & Patron user are already testing it. See the [Status of Chromium-based Port of Nuvola](https://medium.com/nuvola-news/nuvola-chromium-port-status-3b1648b29c77) blog post.

Closing as a duplicate of tiliado/nuvolaruntime#374

**Closed by fenryxo** 2018-01-08 15:03 UTC
Labels: duplicate

**Comment by leandroramos** [comment] 2018-01-08 15:12
Oh, thank you!
