### ISSUE TITLE
Cannot login through facebook

### ISSUE THREAD

**Issue by sasann** [tiliado/nuvola-app-spotify#8] opened 2015-09-06 22:21 UTC
Hello,
I have Nuvola and Spotify plugin both installed from git but I cannot login to Spotify through Facebook.
When I enter my credentials, I get this message:
>Cookies Required
>Cookies are not enabled on your browser. Please enable cookies in your browser preferences to continue.

**Comment by fenryxo** [comment] 2015-09-07 08:53
Hello. Thanks for taking the time to report your issue. I need more information to investigate it further:

* Your system.
* Debugging output from terminal during the whole logging in sequence.
* Whether the issue is reproducible in WebKitGtk MiniBrowser.

See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) for details.

**Comment by fenryxo** [comment] 2016-05-17 08:35
Closing as the reporter haven't provided required information.

**Closed by fenryxo** 2016-05-17 08:35 UTC
Labels: bug
